# Generated by Django 2.2.5 on 2020-06-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('stock', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='ecom/photos')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
