# Generated by Django 2.2.5 on 2020-06-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_auto_20200611_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=60)),
                ('contact_no', models.CharField(max_length=14)),
                ('street_address', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=20)),
                ('zip', models.CharField(max_length=100)),
            ],
        ),
    ]
