# Generated by Django 2.2.5 on 2021-08-03 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_order_order_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date']},
        ),
    ]
