# Generated by Django 2.2.5 on 2021-08-05 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_auto_20210804_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
