# Generated by Django 2.2.5 on 2021-07-26 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200617_0129'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('ecom', '0008_order_order_address'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
